### ISSUE TITLE
Add CMake config files to the package

### ISSUE THREAD

**Issue by niosHD** [vthiery/conan-jsonformoderncpp#16]
Would it be possible to package the CMake config files that get installed with the library (i.e., `nlohmann_jsonConfig.cmake`, `nlohmann_jsonConfigVersion.cmake`, and `nlohmann_jsonTargets.cmake`)? Having them in the conan package would allow to use the regular `find_package(nlohmann_json)` CMake syntax in consuming packages.

**Comment by vthiery** [comment]
Hi!
Why not relying on [conan_basic_setup](http://docs.conan.io/en/latest/integrations/cmake/cmake_generator.html#targets-approach) actually?

**Comment by niosHD** [comment]
Hi!

If you solely rely on conan, nothing. However, I have some projects which have to compile standalone with installed dependencies as well as with conan. For these projects I prefer to rely on the CMake `find_package` functionality because that works with and without conan (when the config files are packaged).

Given that the CMake-based build system of the library can already generate the needed config files during installation they should be easy to add. If you want I can provide a PR.

Best,
Mario

**Comment by vthiery** [comment]
Hmm ok I understand now thanks. I'm still not sure how 'standard' this approach is for header-only packages... @memsharded, is adding the generated .cmake files in the package considered a good practice?

**Comment by memsharded** [comment]
Yes, why not. It makes them available to those users wanting to use find_package functionality, conan can provide the cmake module paths (basically pointing to the root of each package, where the cmake find scripts are expected to be).

You can see some discussion in https://github.com/conan-io/conan/issues/2463#issuecomment-368299416. I am not a big fan of the find_package functionality, but it is harmless to provide them in the package.

**Comment by vthiery** [comment]
Ok thanks! @niosHD, feel free to throw a PR
