### ISSUE TITLE
Json for modern C++ accepted compilers/platforms

### ISSUE THREAD

**Issue by memsharded** [vthiery/conan-jsonformoderncpp#2]
Header-only libs have a small problem. As they are not compiled in all platforms, users can consume them, but that doesn't mean that the package will work for them.

A good practice in conan packages for header-only libs is to provide a ``configure()`` method that launches exceptions for not supported compilers, something like this:

```python
def configure(self):
      if self.settings.os == "Windows":
            raise Exception("This library XXX is not supported in Windows")
      if self.settings.compiler == "gcc" and str(self.settings.compiler.version) in ["4.8", "4.9"]:
            raise Exception("Old gcc <5.1 versions are not supported")
```

This is requested by the guidelines:
>Raise errors on invalid configurations: If the library doesn’t work for a specific configuration, e.j requires gcc>7 the recipe must contain a configure(self) method that raises an exception in case of invalid settings/options.

Do you know which are the supported platforms of this lib?

**Comment by vthiery** [comment]
The list of arch/compiler under which the library is tested can actually be found here: [supported-compilers](https://github.com/nlohmann/json#supported-compilers).

I will specify them is the `configure` method and throw if the compiler version is not in the list.

Also, keeping in mind that the library is header-only, would it make sense to have more os/compilers tested in the travis pipeline?

**Comment by memsharded** [comment]
Great! Please ping me when you have the configure() method ready.

We think it is not necessary, in the sense that the library author is the one responsible for their code to work under different platforms. Package creators typically have to check/test that the package is correctly created/built. For header-only libraries, having just one CI system for one configuration is enough, so IMO it is not necessary to add more OS/compilers to the travis jobs.

**Comment by vthiery** [comment]
@memsharded I did a PR [here](https://github.com/vthiery/conan-jsonformoderncpp/pull/3) so that you can give some feeback before merging.

**Comment by vthiery** [comment]
As discussed [here](https://github.com/vthiery/conan-jsonformoderncpp/pull/3) this package shall not offer settings and shall not check the compilers in the `configure` method.
