### ISSUE TITLE
The same package cannot currently be used for Windows x86 and x86_64

### ISSUE THREAD

**Issue by Adnn** [vthiery/conan-jsonformoderncpp#43]
Hi,

While testing some of our projects on Windows, we realized the following:
We were routinely using the default profile (so `arch` and `arch_host` were both `x86_64`), and the package was working flawlessly.
Yet, as need to build for `x86` appeared. And we realized that while Conan is trying to use the same package (because of `self.info.header_only()`), our CMake scripts breaks because it finds a CMake package there, but this package cannot be used (because CMake somehow realize it is a 64 bits CMake package, and declines it).

If we remove the package from Conan cache and try again, it rebuilds the package with `arch` set to `x86` and then works for 32 bits builds.

Thank you very much for maintaining this recipe for Conan !

**Comment by vthiery** [comment]
Hi, thanks for raising this issue.

I suppose that ideally, we should not even define the `arch` (and the other) settings [here](https://github.com/vthiery/conan-jsonformoderncpp/blob/master/conanfile.py#L8). It was introduced in #17 to be able to use the CMake helper but I don't know whether it's still required or not.

**Comment by vthiery** [comment]
Actually, a recipe for nlohmann/json has been added to the [conan-center-index](https://github.com/conan-io/conan-center-index/blob/e448e77c951997450a77e1576ab5c0c790aa22b1/recipes/nlohmann_json/all/conanfile.py). I was not aware of that but I guess it would make sense to use theirs if you rely on [3.7.0](https://conan.io/center/nlohmann_json/3.7.0/) or [3.7.3](https://conan.io/center/nlohmann_json/3.7.3/) already. It'd also probably make more sense to create an issue [here](https://github.com/conan-io/conan-center-index/issues), referencing this ticket (but maybe [this PR](https://github.com/conan-io/conan-center-index/pull/1258) will solve your issue already).

Also, now that an "official" recipe is maintained, I will probably stop maintaining this repository and stop releasing new packages.

**Comment by vthiery** [comment]
Closing this, issues can be raised [here](https://github.com/conan-io/conan-center-index) from now on.
